# CI for application

name: Techtrend webapp CI

on:
  push:
    branches: [main]
    paths:
      - "containers/app/**"
      - ".github/workflows/application.yml"
  # pull_request:
  #   branches: [main]
  schedule:
    - cron: "0 19 * * 6" # 7pm (UTC) on Saturday

jobs:
  build_deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: paulhatch/semantic-version@v5.0.2
        id: git-semver
        with:
          tag_prefix: "v"
          major_pattern: "(MAJOR)"
          minor_pattern: "(MINOR)"
          version_format: "${major}.${minor}.${patch}"
          bump_each_commit: false
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push to DockerHub
        uses: docker/build-push-action@v4
        with:
          context: ./containers/app/
          file: ./containers/app/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/appsilon:${{ steps.git-semver.outputs.version }}
      - name: Tag and push current repo code
        run: |
          git tag ${{ steps.git-semver.outputs.version_tag }}
          git push origin ${{ steps.git-semver.outputs.version_tag }}
